In [1]:
%pip install -e .


Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels
Obtaining file:///home/f73aeabd-6de4-471d-92a9-1ba552ae6153/quantum_gate_package
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
  Building editable for quantum-gate-package (pyproject.toml) ... done
  Created wheel for quantum-gate-package: filename=quantum_gate_package-0.1.0-0.editable-py3-none-any.whl size=2666 sha256=981e0cdc23b5ae135961205746184a037698b8f2c19f620d797088228ff053e6
  Stored in directory: /tmp/pip-ephem-wheel-cache-pv5u5wvn/wheels/45/66/58/dc14618a1e26d2f61af2e37a95fe8cf02dbf3f4c2ee1c42e86
Successfully built quantum-gate-package
  Attempting uninstall: quantum-gate-package
    Found existing installation: quantum-gate-package 0.1.0
    Uninstalling quantum-gate-package-0.1.0:
      Successfully

In [6]:
from quantum_gate_package import I, X, Y, Z, H, P0, P1, controlled_gate, projectors, U_two_gates, born_rule_probs, sample_from_probs, measurement_density_matrix, measure_pure_state 


General control gate (Controlled-U) for an N-qubit quantum register

Control and target qubits can be at any position 

In [58]:
import numpy as np

#Example 1
N = 2 

# Control = last qubit, Target = first qubit
control = 0
target = 1
CNOT2_0 = controlled_gate(X, control, target, N)
print(CNOT2_0)

# Example 2: 2-qubit CNOT (control=1, target=0)
N = 2
control = 1
target = 0

CNOT_2_0 = controlled_gate(X, control, target, N)
print(CNOT_2_0)

[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j]]
[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]]


In [ ]:
import numpy as np

#Example 1
N = 3 

# Control = last qubit, Target = first qubit
control = 2
target = 0
CNOT2_0 = controlled_gate(X, control, target, N)
print(CNOT2_0)

# Example 2: 3-qubit CNOT (control=2, target=0)
N = 3
control = 0
target = 1

CNOT_2_0 = controlled_gate(X, control, target, N)
print(CNOT_2_0)

# Example 3: 2-qubit CNOT (control=2, target=0)
N =2
control =1
target = 0

CNOT= controlled_gate(X, control, target, N)
print(CNOT)

N = 4
control = 0
target = 3

C_X = controlled_gate(I, control, target, N)
print(C_X)

In [ ]:
import numpy as np

#Example
N = 3
i = 2
j = 2

U_full = U_two_gates(X, X, i, j, N)

initial_state = np.zeros(2**N)
initial_state[7] = 1

state_after_U = U_full @ initial_state
print(state_after_U)

Create a function that generates a complete set of projectors in computational basis {𝑃𝑖}, 

𝑃𝑖=∣𝑖⟩⟨𝑖∣

In [ ]:
import numpy as np

    #Example_1
P = projectors(2)
print(P[0])
print(P[1])

 #Example_2
P = projectors(4)
print(P[0])
print(P[3])
print(P[1])
print(P[2])

 #Example_3
P = projectors(8)
print(P[0])
print(P[7])

In [10]:
import numpy as np

dim = 4
i = 3

ket = np.zeros(dim)
ket[i] = 0

P = np.outer(ket, ket.conj())  # |i><i|
print("ket =", ket)
print("Projector P =\n", P)


ket = [0. 0. 0. 0.]
Projector P =
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [68]:
try:
    controlled_gate(X, 1, 0, 2)
except ValueError as e:
    print("✅ Error:", e)

1) np.append(a, values)`
Adds new values to the end of an array.

2) np.clip(x, min_value, max_value)`
Limits array values into a fixed range:
- values below `min_value` become `min_value`
- values above `max_value` become `max_value`

3) np.sum(x)`
Returns the total sum of all elements in the array `x`.

4) np.random`
NumPy module used to generate random numbers.

5) np.random.choice(n, p=probs)`
Randomly selects one index from `0, 1, 2, ..., n-1`.
If `p=probs` is given, the selection follows the probability distribution `probs`.

6) np.isclose(a, b)`
Checks if two numbers are approximately equal (close enough),
useful because floating-point numbers may have small numerical errors.

7) rho.shape`
Returns the dimensions (size) of an array.
Example: if `rho` is a matrix, `rho.shape` might be `(4,4)`.

8) rho.shape[0]`
Returns the number of rows of the array `rho`.
9) np.cumsum(x)`
Computes the **cumulative sum** of an array.

Meaning: each element becomes the sum of all previous elements up to that position.

10) np.random.choice(n, p=probs)

Randomly selects one index from 0, 1, 2, ..., n-1.

If p=probs is given, the selection follows the probability distribution probs.


The POVM element Fi is associated with the measurement outcome i, such that the probability of obtaining it when making a measurement on the quantum state ρ is given by:
p(i)=tr(ρFi)

where tr is the trace operator. This is the POVM version of the Born rule. When the quantum state being measured is a pure state |ψ⟩  this formula reduces to:


p(i)=tr(|ψ⟩⟨ψ|Fi)= ⟨ψ|Fi|ψ⟩


In [54]:
rho = np.array([[0.6, 0],
                [0, 0.4]], dtype=complex)

projectors = [Z]

p = born_rule_probs(rho, projectors)
print("Probability vector p =", p)

Probability vector p = [1.]


## 3) Sampling function (choose outcome from p)

Goal: sample one measurement outcome index **k** using the probability vector **p**.

Nice method 1 (recommended, simple):
- Use: `np.random.choice`

outcome = np.random.choice(len(p), p=p)

This directly selects an outcome based on probabilities.


In [65]:
import numpy as np

probs = [0.7, 0.2, 0.1]  # probabilities for outcomes 0,1,2

# take 4 random samples
for i in range(7):
    outcome = sample_from_probs(probs)
    print(outcome)

1
0
0
1
2
1
0


## 4) Measurement function (Outcome + post-measurement state)

Goal: make a full measurement function that returns:
- outcome (k)
- probabilities p
- post-measurement state or  ρ_post

Steps:
1) Compute probabilities: pₖ = Tr(Pₖ ρ)
2) Sample the outcome k from p
3) Update the state using projection:

ρ_post = (Pₖ ρ Pₖ) / Tr(Pₖ ρ)

Return:
(outcome, ρ_post, p)


In [60]:
F0 = np.array([[0.7, 0],
               [0,   0.2]], dtype=complex)

F1 = np.eye(2, dtype=complex) - F0   # because F0 + F1 = I

psi = np.array([1, 1], dtype=complex) / np.sqrt(2)   # (|0>+|1>)/√2
rho = np.outer(psi, psi.conj())                      # rho = |psi><psi|

p0 = np.trace(rho @ F0)
p1 = np.trace(rho @ F1)

print("p0 =", np.real(p0))
print("p1 =", np.real(p1))

p0 = 0.4499999999999999
p1 = 0.5499999999999999


In [62]:
import numpy as np

projectors = [P0, P1]

rho = np.array([[1, 0],
                [0, 0]], dtype=complex)   # |1><1|

outcome, rho_post, probs = measurement_density_matrix(rho, projectors)

print("Probabilities:", probs)
print("Outcome:", outcome)
print("Post-measurement state:\n", rho_post)

Probabilities: [1. 0.]
Outcome: 0
Post-measurement state:
 [[1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]
