In [ ]:
%pip install numpy matplotlib
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels


In [2]:
from quantum_gate_package import I, X, H, U_N_qubits, P0, P1, U_one_gate, U_two_gates,rho,evolve

In [3]:
import numpy as np
CNOT= np.kron(P0, I) + np.kron(P1, X)
print(CNOT)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]


Case 2: Control = second qubit, Target = first qubit
          CNOT1→0=I⊗P0+X⊗P1

In [4]:
import numpy as np
CNOT= np.kron(I, P0) + np.kron(X, P1)
print(CNOT)

#Example 
initial_state=np.array((1,0,0,0))
final_state=CNOT@initial_state
print(final_state)

[[1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]]
[1 0 0 0]


In [9]:
import numpy as np

#Example
N = 3
i = 2
j = 2
U_full = U_two_gates(X, X, i, j, N)
initial_state = np.zeros(2**N)
initial_state[7] = 1

state_after_U = U_full @ initial_state
print(state_after_U)

[0. 0. 0. 0. 0. 0. 0. 1.]
